package PM;

import javax.swing.JOptionPane;

// @author gigatore
public class homeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    private javax.swing.JButton logsButton;
    private javax.swing.JButton manageTenantButton;
    private javax.swing.JLabel  userIndicatorLabel;

    public homeAdmin() {
        initComponents();

        logsButton = new javax.swing.JButton();
        logsButton.setBackground(new java.awt.Color(0, 204, 153));
        logsButton.setFont(new java.awt.Font("Lucida Grande", java.awt.Font.BOLD, 14));
        logsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/manage.png")));
        logsButton.setText("Access Logs");
        logsButton.addActionListener(e -> new logs().setVisible(true));
        getContentPane().add(logsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 740, 250, 80));
        getContentPane().setComponentZOrder(logsButton, 0);

        manageTenantButton = new javax.swing.JButton();
        manageTenantButton.setBackground(new java.awt.Color(0, 204, 153));
        manageTenantButton.setFont(new java.awt.Font("Lucida Grande", java.awt.Font.BOLD, 14));
        manageTenantButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/manage.png")));
        manageTenantButton.setText("ManageTenant");
        manageTenantButton.addActionListener(e -> new manageTenant().setVisible(true));
        getContentPane().add(manageTenantButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 395, 250, 80));
        getContentPane().setComponentZOrder(manageTenantButton, 0);

        configureButtonsForRole();

        userIndicatorLabel = new javax.swing.JLabel();
        String displayName = (Session.nome != null ? Session.nome : "") +
                             " " +
                             (Session.cognome != null ? Session.cognome : "");
        userIndicatorLabel.setText(displayName.trim());
        userIndicatorLabel.setFont(new java.awt.Font("Lucida Grande", java.awt.Font.BOLD, 13));
        userIndicatorLabel.setForeground(java.awt.Color.WHITE);
        userIndicatorLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/manage.png")));
        userIndicatorLabel.setIconTextGap(8);
        getContentPane().add(userIndicatorLabel,
            new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 8, 260, 35));
        getContentPane().setComponentZOrder(userIndicatorLabel, 0);
    }

    private void configureButtonsForRole() {
        String rt = Session.roleType != null ? Session.roleType : "";
        boolean isAS = "AS".equalsIgnoreCase(rt);
        boolean isAC = "AC".equalsIgnoreCase(rt);
        boolean isAR = "AR".equalsIgnoreCase(rt);

        // ManageUser: tutti i ruoli (U vede solo la propria utenza, gestito in manageUser.java)
        muserButton.setVisible(true);
        // ManageRiservation: AS, AC, AR
        mriservationButton.setVisible(true);
        // ManageRoom: AS, AC
        mroomButton.setVisible(isAS || isAC);
        // ManageTenant: solo AS
        manageTenantButton.setVisible(isAS);
        // CheckIn, CheckOut: tutti
        checkinButton.setVisible(true);
        checkoutButton.setVisible(true);
        // Access Logs: AS, AC
        logsButton.setVisible(isAS || isAC);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        mriservationButton = new javax.swing.JButton();
        mroomButton = new javax.swing.JButton();
        checkinButton = new javax.swing.JButton();
        checkoutButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        muserButton = new javax.swing.JButton();
        bgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 0, 50, 40));

        mriservationButton.setBackground(new java.awt.Color(0, 204, 153));
        mriservationButton.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        mriservationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/manage.png"))); // NOI18N
        mriservationButton.setText("ManageRiservation");
        mriservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mriservationButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mriservationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 165, 250, 80));

        mroomButton.setBackground(new java.awt.Color(0, 204, 153));
        mroomButton.setFont(new java.awt.Font(".AppleSystemUIFont", 3, 14)); // NOI18N
        mroomButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/manage.png"))); // NOI18N
        mroomButton.setText("ManageRoom");
        mroomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mroomButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mroomButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 280, 250, 80));

        checkinButton.setBackground(new java.awt.Color(0, 204, 153));
        checkinButton.setFont(new java.awt.Font(".AppleSystemUIFont", 3, 14)); // NOI18N
        checkinButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Customer Registration & Check IN.png"))); // NOI18N
        checkinButton.setText("CheckIn");
        checkinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkinButtonActionPerformed(evt);
            }
        });
        getContentPane().add(checkinButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 510, 250, 80));

        checkoutButton.setBackground(new java.awt.Color(0, 204, 153));
        checkoutButton.setFont(new java.awt.Font(".AppleSystemUIFont", 3, 14)); // NOI18N
        checkoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/out.jpg"))); // NOI18N
        checkoutButton.setText("CheckOut");
        checkoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(checkoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 625, 250, 80));

        logoutButton.setBackground(new java.awt.Color(255, 0, 0));
        logoutButton.setFont(new java.awt.Font(".AppleSystemUIFont", 3, 14)); // NOI18N
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/log out.jpg"))); // NOI18N
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 855, 250, 80));

        muserButton.setBackground(new java.awt.Color(0, 204, 153));
        muserButton.setFont(new java.awt.Font(".SF NS Text", 3, 14)); // NOI18N
        muserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/manage.png"))); // NOI18N
        muserButton.setText("ManageUser");
        muserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muserButtonActionPerformed(evt);
            }
        });
        getContentPane().add(muserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 50, 250, 80));

        bgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.jpg"))); // NOI18N
        getContentPane().add(bgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 1630, 1060));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mroomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mroomButtonActionPerformed
        // TODO add your handling code here:
        new manageRoom().setVisible(true);
    }//GEN-LAST:event_mroomButtonActionPerformed

    private void registraLogout() {
        try {
            java.sql.Connection c = DBConfig.getConnection();
            if (Session.logId >= 0) {
                java.sql.PreparedStatement p = c.prepareStatement(
                    "UPDATE AccessLog SET logout_time=NOW() WHERE log_id=?");
                p.setInt(1, Session.logId);
                p.executeUpdate();
            }
            if (Session.sessionToken != null) {
                java.sql.PreparedStatement p = c.prepareStatement(
                    "UPDATE sessions SET expires=NOW() WHERE token=?");
                p.setString(1, Session.sessionToken);
                p.executeUpdate();
            }
            c.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            Session.logId        = -1;
            Session.userCounter  = null;
            Session.roleType     = null;
            Session.roleId       = -1;
            Session.sessionToken = null;
            Session.committenteId = -1;
        }
    }

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        int yes=JOptionPane.showConfirmDialog(this, "Confirm ?","Exit",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(yes==JOptionPane.YES_OPTION){
            registraLogout();
            new login().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        int yes=JOptionPane.showConfirmDialog(this, "Confirm ?","Exit",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(yes==JOptionPane.YES_OPTION){
            registraLogout();
            System.exit(0);
        }
    }//GEN-LAST:event_closeButtonActionPerformed

    private void muserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muserButtonActionPerformed
        // TODO add your handling code here:
        
        new manageUser().setVisible(true);
    }//GEN-LAST:event_muserButtonActionPerformed

    private void mriservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mriservationButtonActionPerformed
        // TODO add your handling code here:
        
         new manageRiservation().setVisible(true);
    }//GEN-LAST:event_mriservationButtonActionPerformed

    private void checkinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkinButtonActionPerformed
        // TODO add your handling code here:
        
        new checkIn().setVisible(true);
    }//GEN-LAST:event_checkinButtonActionPerformed

    private void checkoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutButtonActionPerformed
        // TODO add your handling code here:
        
        new checkOut().setVisible(true);
    }//GEN-LAST:event_checkoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLabel;
    private javax.swing.JButton checkinButton;
    private javax.swing.JButton checkoutButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton mriservationButton;
    private javax.swing.JButton mroomButton;
    private javax.swing.JButton muserButton;
    // End of variables declaration//GEN-END:variables
}
