package PM;

import com.mysql.cj.xdevapi.Statement;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


// @author gigatore
 
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    //Var per gestire la label della visibilita delle pw
    int flag=0;
    
    public login() {
        initComponents();
        java.awt.Font uiFont = new java.awt.Font("Lucida Grande", java.awt.Font.BOLD, 14);
        formNameLabel.setFont(new java.awt.Font("Lucida Grande", java.awt.Font.BOLD, 18));
        userIdLabel.setFont(uiFont);
        PwLabel.setFont(uiFont);
        emailTextField.setFont(uiFont);
        PwPasswordField.setFont(uiFont);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        formLoginPanel = new javax.swing.JPanel();
        formNameLabel = new javax.swing.JLabel();
        userIdLabel = new javax.swing.JLabel();
        PwLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        PwPasswordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        registrationButton = new javax.swing.JButton();
        forgotPwButton = new javax.swing.JButton();
        visibilitaPwLabel = new javax.swing.JLabel();
        sfondoFotoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 0, 40, 42));

        formNameLabel.setFont(new java.awt.Font("Symbol", 1, 18)); // NOI18N
        formNameLabel.setText("Sign In");

        userIdLabel.setFont(new java.awt.Font("Symbol", 1, 18)); // NOI18N
        userIdLabel.setText("Email");

        PwLabel.setFont(new java.awt.Font("Symbol", 1, 18)); // NOI18N
        PwLabel.setText("Password");

        emailTextField.setFont(new java.awt.Font("Symbol", 1, 18)); // NOI18N
        emailTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailTextFieldKeyReleased(evt);
            }
        });

        PwPasswordField.setFont(new java.awt.Font("Symbol", 1, 18)); // NOI18N
        PwPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PwPasswordFieldActionPerformed(evt);
            }
        });
        PwPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PwPasswordFieldKeyPressed(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(0, 204, 153));
        loginButton.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(153, 0, 0));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        registrationButton.setBackground(new java.awt.Color(0, 204, 153));
        registrationButton.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        registrationButton.setForeground(new java.awt.Color(153, 0, 0));
        registrationButton.setText("Signup");
        registrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationButtonActionPerformed(evt);
            }
        });

        forgotPwButton.setBackground(new java.awt.Color(0, 204, 153));
        forgotPwButton.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        forgotPwButton.setForeground(new java.awt.Color(153, 0, 0));
        forgotPwButton.setText("Forgot Password");
        forgotPwButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPwButtonActionPerformed(evt);
            }
        });

        visibilitaPwLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/h.png"))); // NOI18N
        visibilitaPwLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visibilitaPwLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout formLoginPanelLayout = new javax.swing.GroupLayout(formLoginPanel);
        formLoginPanel.setLayout(formLoginPanelLayout);
        formLoginPanelLayout.setHorizontalGroup(
            formLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLoginPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(formLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formLoginPanelLayout.createSequentialGroup()
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(registrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(forgotPwButton))
                    .addGroup(formLoginPanelLayout.createSequentialGroup()
                        .addGroup(formLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PwLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                        .addGap(55, 55, 55)
                        .addGroup(formLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(formLoginPanelLayout.createSequentialGroup()
                                .addGroup(formLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(emailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                    .addComponent(PwPasswordField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(visibilitaPwLabel)))))
                .addGap(42, 42, 42))
        );
        formLoginPanelLayout.setVerticalGroup(
            formLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLoginPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(formNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(formLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(formLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visibilitaPwLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(formLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PwLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PwPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(formLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forgotPwButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        getContentPane().add(formLoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 510, -1));

        sfondoFotoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.jpg"))); // NOI18N
        getContentPane().add(sfondoFotoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 1620, 1050));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void PwPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PwPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PwPasswordFieldActionPerformed

    //bottono login click
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        Statement st = null;
        PreparedStatement pst= null; 
        ResultSet rs;
        try {
            con=DBConfig.getConnection();
            pst=con.prepareStatement("select * from User where email=? AND access=?");
            pst.setString(1,emailTextField.getText());
            pst.setString(2, PwPasswordField.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                pst = con.prepareStatement(
                    "SELECT U.user_counter, U.email, U.nome, U.cognome, U.committente_id, " +
                    "M.role_id, M.role_nome, M.role_type " +
                    "FROM User U JOIN mansione M ON U.ruolo = M.role_id " +
                    "WHERE U.stato=? AND U.email=?");
                pst.setString(1, "attivo");
                pst.setString(2, emailTextField.getText());
                rs = pst.executeQuery();

                if(rs.next()){
                    String userCounter   = rs.getString("U.user_counter");
                    String userEmail     = rs.getString("U.email");
                    String nome          = rs.getString("U.nome");
                    String cognome       = rs.getString("U.cognome");
                    int    committenteId = rs.getInt("U.committente_id");
                    int    roleId        = rs.getInt("M.role_id");
                    String roleNome      = rs.getString("M.role_nome");
                    String roleType      = rs.getString("M.role_type");

                    // AccessLog
                    pst = con.prepareStatement(
                        "INSERT INTO AccessLog(user_id, ip_address, note) VALUES(?,?,?)",
                        java.sql.Statement.RETURN_GENERATED_KEYS);
                    pst.setString(1, userCounter);
                    pst.setString(2, "127.0.0.1");
                    pst.setString(3, "Desktop App");
                    pst.executeUpdate();
                    ResultSet gk = pst.getGeneratedKeys();
                    if (gk.next()) Session.logId = gk.getInt(1);

                    // Session record
                    String token = java.util.UUID.randomUUID().toString().replace("-","") +
                                   java.util.UUID.randomUUID().toString().replace("-","");
                    java.util.Calendar cal = java.util.Calendar.getInstance();
                    cal.add(java.util.Calendar.HOUR, 8);
                    String expires = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(cal.getTime());
                    pst = con.prepareStatement(
                        "INSERT INTO sessions(user_id, committente_id, role_id, token, expires) VALUES(?,?,?,?,?)");
                    pst.setString(1, userCounter);
                    pst.setInt(2, committenteId > 0 ? committenteId : 1);
                    pst.setInt(3, roleId);
                    pst.setString(4, token);
                    pst.setString(5, expires);
                    pst.executeUpdate();

                    // Popola sessione in memoria
                    Session.userCounter   = userCounter;
                    Session.email         = userEmail;
                    Session.nome          = nome;
                    Session.cognome       = cognome;
                    Session.committenteId = committenteId;
                    Session.roleId        = roleId;
                    Session.roleNome      = roleNome;
                    Session.roleType      = roleType;
                    Session.sessionToken  = token;

                    new homeAdmin().setVisible(true);
                    dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this,"Account non attivo o non trovato.","Accesso negato",JOptionPane.INFORMATION_MESSAGE);
                    emailTextField.requestFocus();
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"Incorrect Email ID or Password","Incorrect",JOptionPane.WARNING_MESSAGE);
                emailTextField.requestFocus();
            }           
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Errore di connessione o query:\n" + ex.getMessage(), "Errore DB", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_loginButtonActionPerformed

    
    /// Action del bottone rosso exit
    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        int yes=JOptionPane.showConfirmDialog(this, "Confirm ?","Exit",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(yes==JOptionPane.YES_OPTION){
            System.exit(0);
        }       
    }//GEN-LAST:event_closeButtonActionPerformed

    //click per visibilita o meno della pw
    private void visibilitaPwLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visibilitaPwLabelMouseClicked
        // TODO add your handling code here:
        if(flag==0){
            visibilitaPwLabel.setIcon(new ImageIcon(getClass().getResource("/image/s.png")));
            flag=1;
            PwPasswordField.setEchoChar((char)0);
        }
        else
        {
            visibilitaPwLabel.setIcon(new ImageIcon(getClass().getResource("/image/h.png")));
            flag=0;
            PwPasswordField.setEchoChar('*');
        }
    }//GEN-LAST:event_visibilitaPwLabelMouseClicked
// bottone signup
    private void registrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationButtonActionPerformed
        // TODO add your handling code here
        new registration().setVisible(true);
    }//GEN-LAST:event_registrationButtonActionPerformed

    private void forgotPwButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPwButtonActionPerformed
        // TODO add your handling code here:
        new passWord().setVisible(true);
    }//GEN-LAST:event_forgotPwButtonActionPerformed

    private void emailTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTextFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        PwPasswordField.requestFocus();
        }
    }//GEN-LAST:event_emailTextFieldKeyPressed

    private void PwPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PwPasswordFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            loginButton.doClick();
        }
    }//GEN-LAST:event_PwPasswordFieldKeyPressed

    private void emailTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTextFieldKeyReleased
        // TODO add your handling code here:
        emailTextField.setText(emailTextField.getText().toLowerCase()); 

        String email = emailTextField.getText();
        if (isValidEmail(email)) {
            userIdLabel.setText("Email valida ✅");
            userIdLabel.setForeground(Color.GREEN);
        } else {
            userIdLabel.setText("Email non valida ❌");
            userIdLabel.setForeground(Color.RED);
        }
        if(emailTextField.getText().equals("")){
            userIdLabel.setText("");
        }
            
    }//GEN-LAST:event_emailTextFieldKeyReleased

    private boolean isValidEmail(String email) {
        String emailRegex = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$";
        return Pattern.matches(emailRegex, email);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PwLabel;
    private javax.swing.JPasswordField PwPasswordField;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton forgotPwButton;
    private javax.swing.JPanel formLoginPanel;
    private javax.swing.JLabel formNameLabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton registrationButton;
    private javax.swing.JLabel sfondoFotoLabel;
    private javax.swing.JLabel userIdLabel;
    private javax.swing.JLabel visibilitaPwLabel;
    // End of variables declaration//GEN-END:variables
}
