package PM;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


 //@author gigatore
 
public class manageRoom extends javax.swing.JFrame {

    /**
     * Creates new form manageRoom
     */
    public manageRoom() {
        initComponents();
        Connect();
        autoID();
        Load_room();
        
       // s();     
    }
    
    Connection con;
    PreparedStatement pst;
    DefaultTableModel d;
    String s2;
    
    // per la connection string
    public void Connect()
    {
        try{
            con = DBConfig.getConnection();
        } catch (SQLException ex) {
            Logger.getLogger(manageRoom.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    // per recuperare l'ultimo numero
    public int convInt(String num){
        int ris;
        ris = Integer.parseInt(num.substring(1));  
        return ris;   
    }
    
    //metodo per visualizzare il la l'id della camera in modo alphanumerico
    public String convAlfa(int num){
        String ris;
        ris = "R0" + String.format("%03d",num);
        return ris;   
    }
    
    // per l'identificatore
    public void autoID()
    {
        try {
            PreparedStatement pst1 = con.prepareStatement("select Max(room_id) from Room");
            ResultSet rs = pst1.executeQuery();
            if(rs.next() && rs.getObject(1) != null){
                int id = ((Number) rs.getObject(1)).intValue();
                id++;
                rnTextField.setText(convAlfa(id));
            }
            else{
                rnTextField.setText("R0001");
            }
            
              
        } catch (SQLException ex) {
            Logger.getLogger(manageRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // caricamento delle camere
    public void Load_room()
    {
        String id ;
        int c; 
        try {
            pst = con.prepareStatement("select room_id,tipo,prezzo,letto_tipo,stato from Room");
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData rsd = (ResultSetMetaData) rs.getMetaData();
            c = rsd.getColumnCount();  
            d = (DefaultTableModel)roomTable.getModel();
            d.setRowCount(0);
            
            // aggiungere le righe
            while(rs.next())
            {
                id = convAlfa(rs.getInt("room_id"));
                Vector v2 = new Vector();
                v2.add(id);
                v2.add(rs.getString("tipo"));
                v2.add(rs.getString("letto_tipo"));
                v2.add(rs.getString("prezzo"));
                v2.add(rs.getString("stato"));
                d.addRow(v2);
            }
            updateButton.setEnabled(false);
                
        } catch (SQLException ex) {
            Logger.getLogger(manageRoom.class.getName()).log(Level.SEVERE, null, ex);
        }         
    }
    

    public void clear(){
        autoID();
        rnTextField.setEditable(false);
        rtComboBox.setSelectedIndex(0);
        btComboBox.setSelectedIndex(0);
        priceTextField.setText("");
        addrButton.setEnabled(true);
        updateButton.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        logoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        roomTable = new javax.swing.JTable();
        rnLabel = new javax.swing.JLabel();
        rnTextField = new javax.swing.JTextField();
        btLabel = new javax.swing.JLabel();
        btComboBox = new javax.swing.JComboBox<>();
        rtLabel = new javax.swing.JLabel();
        rtComboBox = new javax.swing.JComboBox<>();
        priceLabel = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        addrButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();
        bgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, -1, -1));

        logoLabel.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/manage.png"))); // NOI18N
        logoLabel.setText("    Manage Room");
        getContentPane().add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 16, 184, -1));

        roomTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Room Number", "Room Type", "Bed Type", "Price", "Status"
            }
        ));
        roomTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(roomTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 1110, 420));

        rnLabel.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        rnLabel.setText("Roon Number");
        getContentPane().add(rnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 300, 24));

        rnTextField.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        rnTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rnTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(rnTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 300, 34));

        btLabel.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        btLabel.setText("Bed Type");
        getContentPane().add(btLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 700, 300, 26));

        btComboBox.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        btComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "matrimoniale", "singolo", "king-size", " " }));
        getContentPane().add(btComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 750, 290, 36));

        rtLabel.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        rtLabel.setText("Room Type");
        getContentPane().add(rtLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 570, 313, 35));

        rtComboBox.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        rtComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "singola", "doppia", "suite", " ", " " }));
        getContentPane().add(rtComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 620, 313, 35));

        priceLabel.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        priceLabel.setText("Price");
        getContentPane().add(priceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 700, 313, 25));

        priceTextField.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        priceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(priceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 750, 313, 36));

        addrButton.setBackground(new java.awt.Color(0, 204, 153));
        addrButton.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        addrButton.setForeground(new java.awt.Color(153, 0, 0));
        addrButton.setText("Add Room");
        addrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addrButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 930, 162, 40));

        updateButton.setBackground(new java.awt.Color(0, 204, 153));
        updateButton.setFont(new java.awt.Font(".SF NS Text", 3, 14)); // NOI18N
        updateButton.setForeground(new java.awt.Color(153, 0, 0));
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 930, 150, 40));

        clearButton.setBackground(new java.awt.Color(0, 204, 153));
        clearButton.setFont(new java.awt.Font(".SF NS Text", 3, 14)); // NOI18N
        clearButton.setForeground(new java.awt.Color(153, 0, 0));
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 930, 150, 40));

        messageLabel.setText("Click to update the record!!    Double-click to delete it!!");
        getContentPane().add(messageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 380, 20));

        bgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/all pages background.png"))); // NOI18N
        getContentPane().add(bgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 1040));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rnTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rnTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rnTextFieldActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void addrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrButtonActionPerformed
         
        
        // TODO add your handling code here:
        if(rnTextField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "All Field is Requied");
            rnTextField.requestFocus();
        }
        else if(priceTextField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "All Field is Requied");
            priceTextField.requestFocus();
        }   
        else{   
        
//            PreparedStatement pst=null;
//            Statement st=null;
            ResultSet rs=null;
            try {
                // per recuperare il valore numerico del numero camera
                int id = convInt(rnTextField.getText());
                
//                Class.forName("com.mysql.cj.jdbc.Driver");
//                java.sql.Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pm_collegio","root","Giresse98!");
                // st=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
                pst = con.prepareStatement("select * from Room where room_id=?");
                pst.setInt(1, id);  //kp);
                rs = pst.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(this,"Room Number Already Exist");
                }
                else{
                    try{
                        double pric = Double.parseDouble(priceTextField.getText());
                       
                        try {
//                            Class.forName("com.mysql.cj.jdbc.Driver");
//                            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pm_collegio","root","Giresse98!");

                            pst=con.prepareStatement("insert into Room(room_id,committente_id,numero_stanza,tipo,prezzo,letto_tipo,stato)values(?,?,?,?,?,?,?)");
                            pst.setInt(1, id);
                            pst.setInt(2, 1);
                            pst.setInt(3, id);
                            pst.setString(4, rtComboBox.getItemAt(rtComboBox.getSelectedIndex()));
                            pst.setDouble(5, pric);
                            pst.setString(6, btComboBox.getItemAt(btComboBox.getSelectedIndex()));
                            pst.setString(7, "disponibile");                       
                            pst.executeUpdate();
                            JOptionPane.showMessageDialog(this, "Room Added");
                            //s();
                            autoID();
                            Load_room();
                            priceTextField.setText("");
                            //rnTextField.setText("");
                  
                        } catch (SQLException ex) {
                            //
                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(this,"Price is not valied");
                    }
                
                }
            
             } catch (Exception ex) {
            //Logger.getLogger(Record.class.getName()).log(Level.SEVERE, null, ex);
            }
   
        }    
    }//GEN-LAST:event_addrButtonActionPerformed

    private void roomTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomTableMouseClicked
        // TODO add your handling code here:
        
         
        int count = evt.getClickCount();
        if(count == 1){
            DefaultTableModel dmodel=(DefaultTableModel) roomTable.getModel();
                int rows=roomTable.getSelectedRow();
                s2=(String) dmodel.getValueAt(rows,0);
                String s1=(String) dmodel.getValueAt(rows,4);
                String s3=(String) dmodel.getValueAt(rows,1);
                String s4=(String) dmodel.getValueAt(rows,2);
                String s5=(String) dmodel.getValueAt(rows,3);
                if(s1.equalsIgnoreCase("occupata"))
                   JOptionPane.showMessageDialog(this,"Sorry Room is Booked So unable to Update it");
                else{
                    updateButton.setEnabled(true);
                    addrButton.setEnabled(false);
                    rnTextField.setText(s2);
                    rtComboBox.setSelectedItem(s3);
                    btComboBox.setSelectedItem(s4);
                    priceTextField.setText(s5);
                    rnTextField.setEditable(false);
                }
        }
        else{
            //String check = JOptionPane.showInputDialog(this,"If you want to Delete this Record Write here to Delete\nIf you want to Update this Record then Write here update");
      
            int yes=JOptionPane.showConfirmDialog(this, "Confirm ?","Delete",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(yes==JOptionPane.YES_OPTION){
            //System.exit(0); 
                DefaultTableModel dmodel = (DefaultTableModel) roomTable.getModel();
                int rows = roomTable.getSelectedRow();
                String s1=(String) dmodel.getValueAt(rows,4);
                s2=(String) dmodel.getValueAt(rows,0);
                int id = convInt(s2);
                
                if(s1.equalsIgnoreCase("occupata"))
                   JOptionPane.showMessageDialog(this,"Sorry Room is Booked So unable to delete it");
                else{
                    PreparedStatement pst;
                    //java.sql.Connection con;
                    try {
//                        Class.forName("com.mysql.cj.jdbc.Driver");
//                        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pm_collegio","root","Giresse98!");
                        pst = con.prepareStatement("delete from Room where room_id=?");
                        pst.setInt(1,id);
                        pst.executeUpdate();
                        autoID();
                        Load_room();
                        //s();
                    }
                    catch(SQLException e){
                    }               
                }
            }
                      
        
        }
    }//GEN-LAST:event_roomTableMouseClicked

    private void priceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        if(priceTextField.getText().equals(""))
            JOptionPane.showMessageDialog(this, "All Field id Required");
        else{
                int id = convInt(rnTextField.getText());
                double price = Double.parseDouble(priceTextField.getText());
                String type = rtComboBox.getItemAt(rtComboBox.getSelectedIndex());
                String bed = btComboBox.getItemAt(btComboBox.getSelectedIndex());
                
                PreparedStatement pst;
                //java.sql.Connection con;
                try {
//                    Class.forName("com.mysql.cj.jdbc.Driver");
//                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel", "root", "Sudhir@123");
                    //pst=con.prepareStatement("update room set price="+txtprice.getText()+","+"roomtype="+type+" where roomnumber="+s2);
                    //(room_id,committente_id,numero_stanza,tipo,prezzo,letto_tipo,stato
                    pst=con.prepareStatement("update Room set prezzo=?,tipo=?,letto_tipo=? where room_id=?");
                    pst.setDouble(1,price);
                    pst.setString(2,type);
                    pst.setString(3,bed);
                    pst.setInt(4,id);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Room Updated");
                    autoID();
                    Load_room();
                    addrButton.setEnabled(true);
                    updateButton.setEnabled(false);
                  
                }catch(Exception e){
                    
                }
                }       
    }//GEN-LAST:event_updateButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        
        clear();
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addrButton;
    private javax.swing.JLabel bgLabel;
    private javax.swing.JComboBox<String> btComboBox;
    private javax.swing.JLabel btLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JLabel rnLabel;
    private javax.swing.JTextField rnTextField;
    private javax.swing.JTable roomTable;
    private javax.swing.JComboBox<String> rtComboBox;
    private javax.swing.JLabel rtLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
